name: Cocoloco
favicon: null
layout_spectrum: 0.27295
typography_spectrum: 0.09296
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#072636'
    - '#f0ece3'
    - '#99c0b8'
    - '#575a6c'
    - '#509b9c'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.9109004284255207
  rhythmicContrast: 0.25
purpose: []
