name: Cocoloco
favicon: null
layout_spectrum: 0.23580111609771848
typography_spectrum: 0.5286856857128441
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0001'
    - '#fefefe'
    - '#87cbbc'
    - '#789d96'
    - '#6d6d6d'
  brandStrength: 0.875
  lightness: 0.17396267200820148
  saturation: 0.9109004284255207
  rhythmicContrast: 0.10665442375466228
purpose: []
